[workspace]
resolver = "2"
members = [
    "crates/airplay-core",
    "crates/airplay-crypto",
    "crates/airplay-rtsp",
    "crates/airplay-stream",
    "crates/audio-pipe",
    "crates/app",
]

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1"
thiserror = "2"
sha2 = "0.11"
hkdf = "0.13"
chacha20poly1305 = "0.11"
num-bigint = "0.5"
tokio = { version = "1", features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "signal", "time"] }
rubato = "5.0"
audioadapter-buffers = "5.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
mdns-sd = "0.21"
windows = "0.62"
