[package]
name = "airplay-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "airplay"
path = "src/main.rs"

[dependencies]
airplay-core = { path = "../airplay-core" }
airplay-rtsp = { path = "../airplay-rtsp" }
anyhow.workspace = true
audio-pipe = { path = "../audio-pipe" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true
