[package]
name = "audio-pipe"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
airplay-core = { path = "../airplay-core" }
airplay-crypto = { path = "../airplay-crypto" }
airplay-stream = { path = "../airplay-stream" }
rubato.workspace = true
audioadapter-buffers.workspace = true
tracing.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Media_Audio",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_Devices_FunctionDiscovery",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_System_Variant",
    "Win32_System_Threading",
] }
